name: dorimol
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: lib/assets/fonts/icomoon.ttf

    - family: Rostelecom
      fonts:
        - asset: lib/assets/fonts/Rostelecom-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/Rostelecom-Bold.otf
          weight: 700

  assets:
    - lib/assets/images/categories/fruits.png
    - lib/assets/images/items/item.png