// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ07fC-FFVL-XgumId_caxH5PcKO80FVw',
    appId: '1:1028752678591:web:42dbc891a09f553229300a',
    messagingSenderId: '1028752678591',
    projectId: 'dorimol-pmr',
    authDomain: 'dorimol-pmr.firebaseapp.com',
    storageBucket: 'dorimol-pmr.firebasestorage.app',
    measurementId: 'G-EYG852CW60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbEjaSbPEQpGfDj1-cZyDypF4b43TB1CE',
    appId: '1:1028752678591:android:2a45ebd85284b00929300a',
    messagingSenderId: '1028752678591',
    projectId: 'dorimol-pmr',
    storageBucket: 'dorimol-pmr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqR9YDhvo3cicmIowxiW7szbq2YbKcIpM',
    appId: '1:1028752678591:ios:af2535529dfbc05f29300a',
    messagingSenderId: '1028752678591',
    projectId: 'dorimol-pmr',
    storageBucket: 'dorimol-pmr.firebasestorage.app',
    iosBundleId: 'com.agrotech.dorimol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqR9YDhvo3cicmIowxiW7szbq2YbKcIpM',
    appId: '1:1028752678591:ios:af2535529dfbc05f29300a',
    messagingSenderId: '1028752678591',
    projectId: 'dorimol-pmr',
    storageBucket: 'dorimol-pmr.firebasestorage.app',
    iosBundleId: 'com.agrotech.dorimol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ07fC-FFVL-XgumId_caxH5PcKO80FVw',
    appId: '1:1028752678591:web:a498a748867294e229300a',
    messagingSenderId: '1028752678591',
    projectId: 'dorimol-pmr',
    authDomain: 'dorimol-pmr.firebaseapp.com',
    storageBucket: 'dorimol-pmr.firebasestorage.app',
    measurementId: 'G-QR6ZN6M7ST',
  );

}