// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm5AY21E1mrQdqIwaX0g7KEC6xrxUOOVc',
    appId: '1:279286832272:web:057af508bf495b8a2a8c15',
    messagingSenderId: '279286832272',
    projectId: 'dorimol-firebase',
    authDomain: 'dorimol-firebase.firebaseapp.com',
    storageBucket: 'dorimol-firebase.firebasestorage.app',
    measurementId: 'G-FTGJEEN2YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHuzrGHyBseB6T2sf5BvsMlzaoQWnHpek',
    appId: '1:279286832272:android:ee0edf5babbc24432a8c15',
    messagingSenderId: '279286832272',
    projectId: 'dorimol-firebase',
    storageBucket: 'dorimol-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFC8XqBlk232TLRIxa64SxZ9SA1k0cAfE',
    appId: '1:279286832272:ios:521f57c88234f7eb2a8c15',
    messagingSenderId: '279286832272',
    projectId: 'dorimol-firebase',
    storageBucket: 'dorimol-firebase.firebasestorage.app',
    iosBundleId: 'com.agrotech.dorimol',
  );

}